version: "3.8"

services:
  znode1:
    image: toastyboii/znode:v0.0.1
    hostname: znode1
    env_file: ./znode-1.env
    healthcheck:
      test: ["CMD", "sh", "-c" ,"/home/zookeeper/healthcheck.sh"]
      interval: 60s
      start_period: 20s
      retries: 2
    ports:
      - "2182:2182"

  znode2:
    image: toastyboii/znode:v0.0.1
    hostname: znode2
    env_file: ./znode-2.env
    healthcheck:
      test: ["CMD", "sh", "-c" ,"/home/zookeeper/healthcheck.sh"]
      interval: 60s
      start_period: 20s
      retries: 2
    ports:
      - "2183:2182"

  znode3:
    image: toastyboii/znode:v0.0.1
    hostname: znode3
    env_file: ./znode-3.env
    healthcheck:
      test: ["CMD", "sh", "-c" ,"/home/zookeeper/healthcheck.sh"]
      interval: 60s
      start_period: 20s
      retries: 2
    ports:
      - "2184:2182"

  kafka-broker-1:
#    image: toastyboii/kafka-broker:v0.0.1
    image: toastyboii/confluent-platform-broker:v0.0.1
    hostname: kafka-broker-1
    depends_on:
      znode1:
        condition: service_healthy
      znode2:
        condition: service_healthy
      znode3:
        condition: service_healthy
    healthcheck:
#      test: [ "CMD", "sh", "-c" ,"/home/kafka/healthcheck.sh" ]
      test: [ "CMD", "sh", "-c" ,"/home/confluent/healthcheck.sh" ]
      interval: 60s
      start_period: 20s
      retries: 2
    env_file: ./kafka-1.env
    command: ["configurator"]
#    restart: on-failure
    ports:
      - "19092:19092"
    expose:
      - 9092
      - 19092

  kafka-broker-2:
#    image: toastyboii/kafka-broker:v0.0.1
    image: toastyboii/confluent-platform-broker:v0.0.1
    hostname: kafka-broker-2
    depends_on:
      znode1:
        condition: service_healthy
      znode2:
        condition: service_healthy
      znode3:
        condition: service_healthy
    healthcheck:
#      test: [ "CMD", "sh", "-c" ,"/home/kafka/healthcheck.sh" ]
      test: [ "CMD", "sh", "-c" ,"/home/confluent/healthcheck.sh" ]
      interval: 60s
      start_period: 20s
      retries: 2
    env_file: ./kafka-2.env
    ports:
      - "19093:19092"
    expose:
      - 9092
      - 19092

  kafka-broker-3:
#    image: toastyboii/kafka-broker:v0.0.1
    image: toastyboii/confluent-platform-broker:v0.0.1
    hostname: kafka-broker-3
    depends_on:
      znode1:
        condition: service_healthy
      znode2:
        condition: service_healthy
      znode3:
        condition: service_healthy
    healthcheck:
#      test: [ "CMD", "sh", "-c" ,"/home/kafka/healthcheck.sh" ]
      test: [ "CMD", "sh", "-c" ,"/home/confluent/healthcheck.sh" ]
      interval: 60s
      start_period: 20s
      retries: 2
    env_file: ./kafka-3.env
    ports:
      - "19094:19092"
    expose:
      - 9092
      - 19092

  kafka-broker-4:
#    image: toastyboii/kafka-broker:v0.0.1
    image: toastyboii/confluent-platform-broker:v0.0.1
    hostname: kafka-broker-4
    depends_on:
      znode1:
        condition: service_healthy
      znode2:
        condition: service_healthy
      znode3:
        condition: service_healthy
    healthcheck:
#      test: [ "CMD", "sh", "-c" ,"/home/kafka/healthcheck.sh" ]
      test: [ "CMD", "sh", "-c" ,"/home/confluent/healthcheck.sh" ]
      interval: 60s
      start_period: 20s
      retries: 2
    env_file: ./kafka-4.env
    ports:
      - "19095:19092"
    expose:
      - 9092
      - 19092

  kafka-broker-5:
#    image: toastyboii/kafka-broker:v0.0.1
    image: toastyboii/confluent-platform-broker:v0.0.1
    hostname: kafka-broker-5
    depends_on:
      znode1:
        condition: service_healthy
      znode2:
        condition: service_healthy
      znode3:
        condition: service_healthy
    healthcheck:
#      test: [ "CMD", "sh", "-c" ,"/home/kafka/healthcheck.sh" ]
      test: [ "CMD", "sh", "-c" ,"/home/confluent/healthcheck.sh" ]
      interval: 60s
      start_period: 20s
      retries: 2
    env_file: ./kafka-5.env
    ports:
      - "19096:19092"
    expose:
      - 9092
      - 19092

  python-kafka-admin-client:
    image: toastyboii/python-admin-client:v0.0.1
    hostname: python-kafka-admin-client
    env_file: ./python-admin-client.env
    tty: true
    stdin_open: true
    depends_on:
      kafka-broker-1:
        condition: service_healthy

  schema-registry-1:
    image: toastyboii/confluent-platform-broker:v0.0.1
    hostname: schema-registry-1
    depends_on:
      znode1:
        condition: service_healthy
      znode2:
        condition: service_healthy
      znode3:
        condition: service_healthy
    env_file: ./schema-registry-1.env
    entrypoint: ["sh", "docker-entrypoint-schema-registry.sh"]
    ports:
      - "8081:8081"
      - "9021:9021"
    expose:
      - 8081
      - 9021

  ksql-node-1:
    image: toastyboii/ksql-node:v0.0.1
    hostname: ksql-node-1
    env_file: ./ksql-node-1.env
    depends_on:
      kafka-broker-1:
        condition: service_healthy

  springboot-user-registration-service:
    image: toastyboii/springboot-user-registration-service:v0.0.1
    env_file: ./user-registration-service.env
    depends_on:
      kafka-broker-1:
        condition: service_healthy
    ports:
      - "443:443"
    expose:
      - 443

  springboot-kafka-streams:
    image: toastyboii/springboot-kafka-streams:v0.0.1
    env_file: ./kafka-streams.env
    depends_on:
      kafka-broker-1:
        condition: service_healthy
      springboot-user-registration-service:
        condition: service_started

  spark-master-node:
    image: toastyboii/spark-node:v0.0.1
    hostname: spark-master-node
    #    env_file: ./spark-master-node.env
    ports:
      - "8080:8080"
      - "4040:4040"
    expose:
      - 8080
      - 4040

  spark-worker-node-1:
    image: toastyboii/spark-node:v0.0.1
    hostname: spark-worker-node-1
    depends_on:
      spark-master-node:
        condition: service_started
    #    env_file: ./spark-master-node.env
    entrypoint: ["sh", "docker-worker-entrypoint.sh"]
    command: ["spark://spark-master-node:7077"]
    expose:
      - 8080
      - 4040
      - 22

  spark-worker-node-2:
    image: toastyboii/spark-node:v0.0.1
    hostname: spark-worker-node-2
    depends_on:
      spark-master-node:
        condition: service_started
    #    env_file: ./spark-master-node.env
    entrypoint: [ "sh", "docker-worker-entrypoint.sh" ]
    command: ["spark://spark-master-node:7077"]
    expose:
      - 8080
      - 4040
      - 22

  spark-worker-node-3:
    image: toastyboii/spark-node:v0.0.1
    hostname: spark-worker-node-3
    depends_on:
      spark-master-node:
        condition: service_started
    #    env_file: ./spark-master-node.env
    entrypoint: [ "sh", "docker-worker-entrypoint.sh" ]
    command: ["spark://spark-master-node:7077"]
    expose:
      - 8080
      - 4040
      - 22

  spark-worker-node-4:
    image: toastyboii/spark-node:v0.0.1
    hostname: spark-worker-node-4
    depends_on:
      spark-master-node:
        condition: service_started
    #    env_file: ./spark-master-node.env
    entrypoint: [ "sh", "docker-worker-entrypoint.sh" ]
    command: ["spark://spark-master-node:7077"]
    expose:
      - 8080
      - 4040
      - 22

  spark-worker-node-5:
    image: toastyboii/spark-node:v0.0.1
    hostname: spark-worker-node-5
    depends_on:
      spark-master-node:
        condition: service_started
    #    env_file: ./spark-master-node.env
    entrypoint: [ "sh", "docker-worker-entrypoint.sh" ]
    command: ["spark://spark-master-node:7077"]
    expose:
      - 8080
      - 4040
      - 22

