configuration:
  service:
    base-url: '/user'
    registration-path: ${configuration.service.base-url}/register
    topic: 'user-registration-events'

server:
  ssl:
    key-store: ${SSL_KEYSTORE_LOCATION}
    key-store-password: ${SSL_KEYSTORE_PASS}
    trust-store: file:${SSL_TRUSTSTORE_LOCATION}
    trust-store-password: ${SSL_TRUSTSTORE_PASS}
    key-alias: ${SSL_KEY_ALIAS}
  port: 443

spring:
  application:
    name: 'User Registration Service'
  kafka:
    properties:
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='${SASL_BROKER_ADMIN_USERNAME}' password='${SASL_BROKER_ADMIN_PASS}';
    security:
      protocol: SASL_SSL
    ssl:
      key-password: ${SSL_KEY_PASS}
      key-store-location: file:${SSL_KEYSTORE_LOCATION}
      key-store-password: ${SSL_KEYSTORE_PASS}
      trust-store-location: file:${SSL_TRUSTSTORE_LOCATION}
      trust-store-password: ${SSL_TRUSTSTORE_PASS}
    jaas:
      enabled: true
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: com.github.nicon777.data.schema.serializer.UserSerializer
      client-id: ${PRODUCER_CLIENT_ID}
    template:
      default-topic: ${configuration.service.topic}

