spring:
  application:
    name: 'Demo Streams'
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: SCRAM-SHA-512
        jaas:
          config: org.apache.kafka.common.security.scram.ScramLoginModule required username='${SASL_BROKER_ADMIN_USERNAME}' password='${SASL_BROKER_ADMIN_PASS}';
    security:
      protocol: SASL_SSL
    ssl:
      key-password: ${SSL_KEY_PASS}
      key-store-location: file:${SSL_KEYSTORE_LOCATION}
      key-store-password: ${SSL_KEYSTORE_PASS}
      trust-store-location: file:${SSL_TRUSTSTORE_LOCATION}
      trust-store-password: ${SSL_TRUSTSTORE_PASS}
    jaas:
      enabled: true
    streams:
      bootstrap-servers: ${BOOTSTRAP_SERVERS}
      application-id: ${APPLICATION_ID}
      replication-factor: ${REPLICATION_FACTOR}
      properties:
        default:
          deserialization.exception.handler: com.github.nicon777.streams.exception.CustomStreamExceptionHandler
          key.serde: org.apache.kafka.common.serialization.Serdes$LongSerde
          value.serde: com.github.nicon777.data.schema.serde.UserSerde

topic.user.registration: 'user-registration-events'


